In [1]:
import pandas as pd
import sqlite3

In [2]:
conn = sqlite3.connect("../../data/golf_workbench.db")
cursor = conn.cursor()

In [3]:
pd.DataFrame(cursor.execute("SELECT * FROM dim_course").fetchall())

   0                   1   2
0  1               KHGCC  18
1  2           Noordwijk  18
2  3        Kennemer B-C  18
3  4          Kennemer A   9
4  5  Links Valley North  18
5  6  Links Valley South  18

In [4]:
columns = [description[0] for description in cursor.description]

In [5]:
columns

['course_id', 'course_name', 'num_holes']

In [6]:
pd.DataFrame(cursor.execute("SELECT * FROM dim_tee").fetchall())

     0              1  2    3     4
0    1   White (Full)  1  157  75.2
1    2  White (Short)  1  155  74.7
2    3         Yellow  1  138  72.1
3    4            Red  1  130  68.9
4    5          White  2  143  75.1
5    6          White  3  137  73.1
6    7          White  4  138  37.8
7    8     White (V2)  1  149  76.0
8    9    Yellow (V2)  1  148  72.9
9   10          White  5  133  71.5
10  11          White  6  134  71.3

In [7]:
columns = [description[0] for description in cursor.description]

In [8]:
columns = [description[0] for description in cursor.description]

In [9]:
columns

['tee_id', 'tee_name', 'course_id', 'slope_rating', 'course_rating']

In [10]:
pd.DataFrame(cursor.execute("SELECT * FROM dim_hole").fetchall())

       0  1   2   3  4     5      6 7
0      1  1   1   1  5  13.0  461.0
1      2  1   1   2  5  13.0  461.0
2      3  1   1   3  5  13.0  443.0
3      4  1   1   4  5  13.0  431.0
4      5  1   1   8  5   NaN    NaN
..   ... ..  ..  .. ..   ...    ... ..
184  185  1  18   9  5   NaN    NaN
185  186  2  18   5  4  10.0  400.0
186  187  3  18   6  4   6.0  366.0
187  188  5  18  10  4   NaN    NaN
188  189  6  18  11  5   NaN    NaN

[189 rows x 8 columns]

In [11]:
columns = [description[0] for description in cursor.description]

In [12]:
columns

['hole_id',
 'course_id',
 'hole_number',
 'tee_id',
 'par',
 'stroke_index',
 'hole_length',
 'description']

In [13]:
df_xlsx = pd.read_excel("../../data/raw/score_analyse.xlsx", sheet_name=None)

In [14]:
df_stroke_indices = df_xlsx.get('Stroke Indices')
df_stroke_indices.columns = [col.replace("Hole ", "") for col in df_stroke_indices.columns]
df_stroke_indices.melt(id_vars=["Course", "Tee"], var_name="hole_number", value_name="stroke_index")
df_stroke_indices

,Course,Tee,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,KHGCC,White (Full),13,7,5,11,15,1,9,17,3,12.0,6.0,16.0,2.0,10.0,4.0,14.0,18.0,8.0
1,KHGCC,White (Short),13,7,5,11,15,1,9,17,3,12.0,6.0,16.0,2.0,10.0,4.0,14.0,18.0,8.0
2,KHGCC,Yellow,13,7,5,11,15,1,9,17,3,12.0,6.0,16.0,2.0,10.0,4.0,14.0,18.0,8.0
3,KHGCC,Red,13,7,5,11,15,1,9,17,3,12.0,6.0,16.0,2.0,10.0,4.0,14.0,18.0,8.0
4,Noordwijk,White,13,5,17,1,3,15,7,11,9,2.0,16.0,18.0,6.0,8.0,14.0,4.0,12.0,10.0
5,Kennemer B-C,White,7,17,1,11,5,15,9,13,3,14.0,4.0,10.0,8.0,2.0,16.0,18.0,12.0,6.0
6,Kennemer A,White,5,11,17,13,7,1,9,15,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df_stroke_indices.shape

(7, 20)

In [16]:
df_stroke_indices.columns = [col.replace("Hole ", "") for col in df_stroke_indices.columns]
df_stroke_indices.melt(id_vars=["Course", "Tee"], var_name="hole_number", value_name="stroke_index").dropna()

           Course            Tee hole_number  stroke_index
0           KHGCC   White (Full)           1          13.0
1           KHGCC  White (Short)           1          13.0
2           KHGCC         Yellow           1          13.0
3           KHGCC            Red           1          13.0
4       Noordwijk          White           1          13.0
..            ...            ...         ...           ...
120         KHGCC  White (Short)          18           8.0
121         KHGCC         Yellow          18           8.0
122         KHGCC            Red          18           8.0
123     Noordwijk          White          18          10.0
124  Kennemer B-C          White          18           6.0

[117 rows x 4 columns]

In [17]:
df_xlsx["Course Pars"].drop(columns="Tee").drop_duplicates()

,Course,Par Hole 1,Par Hole 2,Par Hole 3,Par Hole 4,Par Hole 5,Par Hole 6,Par Hole 7,Par Hole 8,Par Hole 9,Par Hole 10,Par Hole 11,Par Hole 12,Par Hole 13,Par Hole 14,Par Hole 15,Par Hole 16,Par Hole 17,Par Hole 18
0,KHGCC,5,4,4,3,5,4,4,3,4,5.0,4.0,3.0,4.0,4.0,4.0,4.0,3.0,5.0
4,Noordwijk,4,5,3,4,4,3,4,4,5,4.0,5.0,3.0,4.0,5.0,4.0,4.0,3.0,4.0
5,Kennemer B-C,4,3,5,4,4,5,4,3,4,4.0,4.0,5.0,4.0,4.0,3.0,5.0,3.0,4.0
6,Kennemer A,4,5,3,4,4,4,5,3,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Links Valley North,5,4,3,4,4,4,4,3,4,5.0,4.0,3.0,4.0,4.0,4.0,4.0,3.0,4.0
8,Links Valley South,5,3,4,4,3,4,3,4,5,5.0,3.0,4.0,4.0,3.0,4.0,3.0,4.0,5.0

In [18]:
df_xlsx["Hole Lengths"]

,Course,Tee,Hole 1,Hole 2,Hole 3,Hole 4,Hole 5,Hole 6,Hole 7,Hole 8,Hole 9,Hole 10,Hole 11,Hole 12,Hole 13,Hole 14,Hole 15,Hole 16,Hole 17,Hole 18
0,KHGCC,White (Full),461,352,350,199,448,428,351,207,329,455.0,377.0,153.0,378.0,389.0,387.0,353.0,147.0,499.0
1,KHGCC,White (Short),461,352,350,199,448,428,351,207,329,455.0,377.0,153.0,378.0,389.0,387.0,263.0,147.0,499.0
2,KHGCC,Yellow,443,339,317,161,432,386,293,185,319,430.0,360.0,143.0,343.0,313.0,330.0,263.0,138.0,462.0
3,KHGCC,Red,431,291,299,149,375,322,280,160,265,388.0,299.0,122.0,303.0,270.0,319.0,243.0,119.0,426.0
4,Noordwijk,White,353,547,152,423,377,171,331,369,509,400.0,457.0,134.0,338.0,514.0,340.0,358.0,186.0,400.0
5,Kennemer B-C,White,411,144,475,301,304,476,334,178,383,328.0,427.0,497.0,342.0,351.0,155.0,434.0,152.0,366.0
6,Kennemer A,White,398,517,139,366,386,330,513,204,380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN