In [1]:
import pandas as pd

In [2]:
df_xlsx = pd.read_excel("../../data/raw/score_analyse.xlsx", sheet_name=None)

/Users/felixvandoorn/workspace/competition_matchplay_analysis/.venv/lib/python3.10/site-packages/openpyxl/worksheet/_reader.py:223: UserWarning: Cell A7 is marked as a date but the serial value 6691479.0 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)

In [3]:
for sheet_name, sheet_df in df_xlsx.items():
    print(sheet_name)

2017
2018
2019
2020
2021
2022
2023
2024
2025
2026
Course Ratings
Course Pars
Hole Lengths
Stroke Indices

In [4]:
df_xlsx['Course Ratings']

                Course            Tee  Par  Course Rating  Slope Rating
0                KHGCC   White (Full)   72           75.2           157
1                KHGCC  White (Short)   72           74.7           155
2                KHGCC         Yellow   72           72.1           138
3                KHGCC            Red   72           68.9           130
4            Noordwijk          White   72           75.1           143
5         Kennemer B-C          White   72           73.1           137
6           Kennemer A          White   36           37.8           138
7                KHGCC     White (V2)   72           76.0           149
8                KHGCC    Yellow (V2)   72           72.9           148
9   Links Valley North          White   70           71.5           133
10  Links Valley South          White   70           71.3           134

In [5]:
df_xlsx['Hole Lengths']

,Course,Tee,Hole 1,Hole 2,Hole 3,Hole 4,Hole 5,Hole 6,Hole 7,Hole 8,Hole 9,Hole 10,Hole 11,Hole 12,Hole 13,Hole 14,Hole 15,Hole 16,Hole 17,Hole 18
0,KHGCC,White (Full),461,352,350,199,448,428,351,207,329,455.0,377.0,153.0,378.0,389.0,387.0,353.0,147.0,499.0
1,KHGCC,White (Short),461,352,350,199,448,428,351,207,329,455.0,377.0,153.0,378.0,389.0,387.0,263.0,147.0,499.0
2,KHGCC,Yellow,443,339,317,161,432,386,293,185,319,430.0,360.0,143.0,343.0,313.0,330.0,263.0,138.0,462.0
3,KHGCC,Red,431,291,299,149,375,322,280,160,265,388.0,299.0,122.0,303.0,270.0,319.0,243.0,119.0,426.0
4,Noordwijk,White,353,547,152,423,377,171,331,369,509,400.0,457.0,134.0,338.0,514.0,340.0,358.0,186.0,400.0
5,Kennemer B-C,White,411,144,475,301,304,476,334,178,383,328.0,427.0,497.0,342.0,351.0,155.0,434.0,152.0,366.0
6,Kennemer A,White,398,517,139,366,386,330,513,204,380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df_pars = df_xlsx['Course Pars'].drop(columns='Tee').drop_duplicates()
df_course = pd.DataFrame(df_pars['Course'])
df_course['num_holes'] = df_pars.notnull().sum(axis=1) - 1
df_course = df_course.reset_index(drop=True)

In [7]:
df_course

               Course  num_holes
0               KHGCC         18
1           Noordwijk         18
2        Kennemer B-C         18
3          Kennemer A          9
4  Links Valley North         18
5  Links Valley South         18

In [8]:
df_pars = df_xlsx['Course Pars'].drop(columns='Tee').drop_duplicates()

In [9]:
df_course

               Course  num_holes
0               KHGCC         18
1           Noordwijk         18
2        Kennemer B-C         18
3          Kennemer A          9
4  Links Valley North         18
5  Links Valley South         18

In [10]:
df_course = pd.DataFrame(df_pars['Course'])
df_course['num_holes'] = df_pars.notnull().sum(axis=1) - 1
df_course = df_course.reset_index(drop=True)

In [11]:
df_course.head()

               Course  num_holes
0               KHGCC         18
1           Noordwijk         18
2        Kennemer B-C         18
3          Kennemer A          9
4  Links Valley North         18

In [12]:
df_course['num_holes'] = df_pars.notnull().sum(axis=1) - 1

In [13]:
df_course.dtypes

Course        object
num_holes    float64
dtype: object

In [14]:
df_pars

,Course,Par Hole 1,Par Hole 2,Par Hole 3,Par Hole 4,Par Hole 5,Par Hole 6,Par Hole 7,Par Hole 8,Par Hole 9,Par Hole 10,Par Hole 11,Par Hole 12,Par Hole 13,Par Hole 14,Par Hole 15,Par Hole 16,Par Hole 17,Par Hole 18
0,KHGCC,5,4,4,3,5,4,4,3,4,5.0,4.0,3.0,4.0,4.0,4.0,4.0,3.0,5.0
4,Noordwijk,4,5,3,4,4,3,4,4,5,4.0,5.0,3.0,4.0,5.0,4.0,4.0,3.0,4.0
5,Kennemer B-C,4,3,5,4,4,5,4,3,4,4.0,4.0,5.0,4.0,4.0,3.0,5.0,3.0,4.0
6,Kennemer A,4,5,3,4,4,4,5,3,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Links Valley North,5,4,3,4,4,4,4,3,4,5.0,4.0,3.0,4.0,4.0,4.0,4.0,3.0,4.0
8,Links Valley South,5,3,4,4,3,4,3,4,5,5.0,3.0,4.0,4.0,3.0,4.0,3.0,4.0,5.0

In [15]:
df_pars

,Course,Par Hole 1,Par Hole 2,Par Hole 3,Par Hole 4,Par Hole 5,Par Hole 6,Par Hole 7,Par Hole 8,Par Hole 9,Par Hole 10,Par Hole 11,Par Hole 12,Par Hole 13,Par Hole 14,Par Hole 15,Par Hole 16,Par Hole 17,Par Hole 18
0,KHGCC,5,4,4,3,5,4,4,3,4,5.0,4.0,3.0,4.0,4.0,4.0,4.0,3.0,5.0
4,Noordwijk,4,5,3,4,4,3,4,4,5,4.0,5.0,3.0,4.0,5.0,4.0,4.0,3.0,4.0
5,Kennemer B-C,4,3,5,4,4,5,4,3,4,4.0,4.0,5.0,4.0,4.0,3.0,5.0,3.0,4.0
6,Kennemer A,4,5,3,4,4,4,5,3,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Links Valley North,5,4,3,4,4,4,4,3,4,5.0,4.0,3.0,4.0,4.0,4.0,4.0,3.0,4.0
8,Links Valley South,5,3,4,4,3,4,3,4,5,5.0,3.0,4.0,4.0,3.0,4.0,3.0,4.0,5.0

In [16]:
df_scores = pd.concat([df_xlsx[year] for year in df_xlsx.keys() if '20' in year])
scores_with_par_df = df_scores.merge(df_pars, on='Course', how='left')

In [17]:
df_xlsx['Course Ratings']

                Course            Tee  Par  Course Rating  Slope Rating
0                KHGCC   White (Full)   72           75.2           157
1                KHGCC  White (Short)   72           74.7           155
2                KHGCC         Yellow   72           72.1           138
3                KHGCC            Red   72           68.9           130
4            Noordwijk          White   72           75.1           143
5         Kennemer B-C          White   72           73.1           137
6           Kennemer A          White   36           37.8           138
7                KHGCC     White (V2)   72           76.0           149
8                KHGCC    Yellow (V2)   72           72.9           148
9   Links Valley North          White   70           71.5           133
10  Links Valley South          White   70           71.3           134

In [18]:
df_xlsx['Course Ratings']['Tee'].unique()

array(['White (Full)', 'White (Short)', 'Yellow', 'Red', 'White',
       'White (V2)', 'Yellow (V2)'], dtype=object)

In [19]:
df_pars

,Course,Par Hole 1,Par Hole 2,Par Hole 3,Par Hole 4,Par Hole 5,Par Hole 6,Par Hole 7,Par Hole 8,Par Hole 9,Par Hole 10,Par Hole 11,Par Hole 12,Par Hole 13,Par Hole 14,Par Hole 15,Par Hole 16,Par Hole 17,Par Hole 18
0,KHGCC,5,4,4,3,5,4,4,3,4,5.0,4.0,3.0,4.0,4.0,4.0,4.0,3.0,5.0
4,Noordwijk,4,5,3,4,4,3,4,4,5,4.0,5.0,3.0,4.0,5.0,4.0,4.0,3.0,4.0
5,Kennemer B-C,4,3,5,4,4,5,4,3,4,4.0,4.0,5.0,4.0,4.0,3.0,5.0,3.0,4.0
6,Kennemer A,4,5,3,4,4,4,5,3,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Links Valley North,5,4,3,4,4,4,4,3,4,5.0,4.0,3.0,4.0,4.0,4.0,4.0,3.0,4.0
8,Links Valley South,5,3,4,4,3,4,3,4,5,5.0,3.0,4.0,4.0,3.0,4.0,3.0,4.0,5.0

In [20]:
df_scores.dtypes

Date       datetime64[ns]
Course             object
Tee                object
Hole 1              int64
Hole 2              int64
Hole 3              int64
Hole 4              int64
Hole 5              int64
Hole 6              int64
Hole 7              int64
Hole 8              int64
Hole 9              int64
Hole 10           float64
Hole 11           float64
Hole 12           float64
Hole 13           float64
Hole 14           float64
Hole 15           float64
Hole 16           float64
Hole 17           float64
Hole 18           float64
PCC               float64
dtype: object

In [21]:
scores_with_par_df = df_scores.merge(df_pars, on='Course', how='left')

In [22]:
hole_col_names = [col for col in scores_with_par_df.columns if 'Hole' in col and 'Par' not in col]
par_col_names = [col for col in scores_with_par_df.columns if 'Par' in col]

In [23]:
score_matrix = scores_with_par_df[hole_col_names].values
par_matrix = scores_with_par_df[par_col_names].values
differential_matrix = score_matrix - par_matrix

In [24]:
score_matrix

array([[4., 4., 6., ..., 3., 4., 5.],
       [5., 5., 4., ..., 4., 3., 5.],
       [6., 5., 4., ..., 6., 3., 6.],
       ...,
       [5., 4., 4., ..., 5., 3., 5.],
       [4., 4., 4., ..., 4., 3., 5.],
       [6., 6., 4., ..., 5., 3., 7.]])

par_frame

In [25]:
score_matrix - par_matrix

array([[-1.,  0.,  2., ..., -1.,  1.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 1.,  1.,  0., ...,  2.,  0.,  1.],
       ...,
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [-1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  2.,  0., ...,  1.,  0.,  2.]])

In [26]:
differential_col_names = [f"Differential Hole {i}" for i in range(1, 19)]

In [27]:
differential_frame = pd.DataFrame(differential_matrix)
differential_frame.columns = differential_col_names

In [28]:
df_scores['Course']

0    KHGCC
1    KHGCC
2    KHGCC
3    KHGCC
4    KHGCC
     ...
3    KHGCC
4    KHGCC
5    KHGCC
6    KHGCC
7    KHGCC
Name: Course, Length: 117, dtype: object

In [29]:
differential_frame['Course'] = df_scores['Course'].values
differential_frame['Tee'] = df_scores['Tee'].values
differential_frame['Date'] = df_scores['Date'].values
ordered_col_names = ['Course', 'Tee', 'Date'] + differential_col_names

In [30]:
differential_frame = differential_frame[ordered_col_names]

In [31]:
differential_frame

,Course,Tee,Date,Differential Hole 1,Differential Hole 2,Differential Hole 3,Differential Hole 4,Differential Hole 5,Differential Hole 6,Differential Hole 7,...,Differential Hole 9,Differential Hole 10,Differential Hole 11,Differential Hole 12,Differential Hole 13,Differential Hole 14,Differential Hole 15,Differential Hole 16,Differential Hole 17,Differential Hole 18
0,KHGCC,Yellow,2017-05-06,-1.0,0.0,2.0,0.0,0.0,1.0,0.0,...,-1.0,-1.0,0.0,1.0,1.0,0.0,1.0,-1.0,1.0,0.0
1,KHGCC,Yellow,2017-07-16,0.0,1.0,0.0,0.0,3.0,0.0,-1.0,...,1.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,KHGCC,White (Full),2017-07-23,1.0,1.0,0.0,0.0,0.0,3.0,0.0,...,0.0,-1.0,0.0,0.0,0.0,1.0,2.0,2.0,0.0,1.0
3,KHGCC,White (Full),2017-08-06,1.0,0.0,1.0,0.0,-1.0,2.0,-1.0,...,0.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,KHGCC,Yellow,2017-08-12,0.0,2.0,1.0,1.0,0.0,0.0,-1.0,...,1.0,-1.0,1.0,0.0,0.0,-1.0,1.0,0.0,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,KHGCC,White (V2),2026-06-27,0.0,1.0,0.0,0.0,-1.0,0.0,0.0,...,1.0,-1.0,0.0,1.0,0.0,2.0,1.0,0.0,0.0,0.0
113,KHGCC,White (V2),2026-08-02,0.0,1.0,0.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0
114,KHGCC,White (V2),2026-08-02,0.0,0.0,0.0,-1.0,0.0,-1.0,1.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0
115,KHGCC,Yellow (V2),2026-08-16,-1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
116,KHGCC,Yellow (V2),2026-09-26,1.0,2.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,2.0,0.0,1.0,1.0,2.0,1.0,0.0,2.0

In [32]:
differential_frame.groupby(['Course', 'Tee'])[differential_col_names].mean()

                                  Differential Hole 1  Differential Hole 2  \
Course             Tee
KHGCC              Red                      -0.500000             1.000000
                   White (Full)              0.027778             0.333333
                   White (Short)            -0.400000             0.200000
                   White (V2)               -0.187500             0.250000
                   Yellow                   -0.325000             0.450000
                   Yellow (V2)               0.300000             0.700000
Kennemer A         White                     0.000000            -0.500000
Kennemer B-C       White                     0.000000             1.500000
Links Valley North White                     0.000000             0.000000
Links Valley South White                     4.000000             0.000000
Noordwijk          White                     0.000000             1.500000

                                  Differential Hole 3  Differential Hole 4  \
Course             Tee
KHGCC              Red                       1.500000             0.000000
                   White (Full)              0.777778             0.583333
                   White (Short)             0.400000             0.400000
                   White (V2)                0.500000             0.625000
                   Yellow                    0.325000             0.350000
                   Yellow (V2)               0.000000             0.300000
Kennemer A         White                    -0.500000             1.000000
Kennemer B-C       White                    -1.000000             0.500000
Links Valley North White                     0.000000             0.000000
Links Valley South White                     1.000000             2.000000
Noordwijk          White                     1.500000             2.500000

                                  Differential Hole 5  Differential Hole 6  \
Course             Tee
KHGCC              Red                       1.000000             0.500000
                   White (Full)              0.416667             1.694444
                   White (Short)             0.000000             0.800000
                   White (V2)               -0.125000             1.000000
                   Yellow                   -0.075000             0.525000
                   Yellow (V2)               0.000000             0.900000
Kennemer A         White                     1.500000             0.000000
Kennemer B-C       White                     0.000000             1.500000
Links Valley North White                     1.000000             1.000000
Links Valley South White                     1.000000             1.000000
Noordwijk          White                     0.000000             1.000000

                                  Differential Hole 7  Differential Hole 8  \
Course             Tee
KHGCC              Red                      -0.500000            -0.500000
                   White (Full)              0.111111             0.416667
                   White (Short)             0.400000             1.200000
                   White (V2)                0.625000             0.562500
                   Yellow                    0.250000             0.600000
                   Yellow (V2)               0.300000             0.700000
Kennemer A         White                     1.000000             0.500000
Kennemer B-C       White                     0.500000             1.000000
Links Valley North White                     1.000000             1.000000
Links Valley South White                    -1.000000             1.000000
Noordwijk          White                     0.000000             0.500000

                                  Differential Hole 9  Differential Hole 10  \
Course             Tee
KHGCC              Red                       0.000000                 -0.50
                   White (Full)              0.555556                  0.00
                   White (Short)             0.800000                  0.00
                   White (V2)                0.312500                 -0.25
                   Yellow                    0.600000                 -0.05
                   Yellow (V2)               0.300000                  0.10
Kennemer A         White                     1.500000                   NaN
Kennemer B-C       White                     0.500000                  1.00
Links Valley North White                     2.000000                  0.00
Links Valley South White                     0.000000                  2.00
Noordwijk          White                     1.000000                  0.00

                                  Differential Hole 11  Differential Hole 12  \
Course             Tee
KHGCC              Red                        0.000000              0.000000
                   White (Full)               0.194444              0.361111
                   White (Short)              0.600000              0.600000
                   White (V2)                 0.250000              0.375000
                   Yellow                     0.200000              0.400000
                   Yellow (V2)                0.800000              0.500000
Kennemer A         White                           NaN                   NaN
Kennemer B-C       White                      1.500000              0.500000
Links Valley North White                      1.000000              0.000000
Links Valley South White                      1.000000             -1.000000
Noordwijk          White                      1.500000              0.000000

                                  Differential Hole 13  Differential Hole 14  \
Course             Tee
KHGCC              Red                        2.000000              1.500000
                   White (Full)               0.777778              1.055556
                   White (Short)              0.200000             -0.400000
                   White (V2)                 0.437500              0.937500
                   Yellow                     0.300000              0.650000
                   Yellow (V2)                0.500000              0.900000
Kennemer A         White                           NaN                   NaN
Kennemer B-C       White                      1.500000              1.500000
Links Valley North White                      0.000000              1.000000
Links Valley South White                      1.000000              2.000000
Noordwijk          White                      0.500000              2.000000

                                  Differential Hole 15  Differential Hole 16  \
Course             Tee
KHGCC              Red                       -0.500000             -1.000000
                   White (Full)               0.472222              0.611111
                   White (Short)              0.800000              0.200000
                   White (V2)                 0.437500              0.250000
                   Yellow                     0.450000              0.200000
                   Yellow (V2)                0.300000              0.700000
Kennemer A         White                           NaN                   NaN
Kennemer B-C       White                      4.000000              0.500000
Links Valley North White                      2.000000              0.000000
Links Valley South White                      0.000000              1.000000
Noordwijk          White                      1.000000              2.500000

                                  Differential Hole 17  Differential Hole 18
Course             Tee
KHGCC              Red                        0.500000             -0.500000
                   White (Full)               0.527778              0.472222
                   White (Short)              0.400000              0.200000
                   White (V2)                 0.437500              0.312500
                   Yellow                     0.275000              0.275000
                   Yellow (V2)                0.600000              0.900000
Kennemer A         White                           NaN                   NaN
Kennemer B-C       White                      1.000000              0.500000
Links Valley North White                      0.000000              4.000000
Links Valley South White                      2.000000              2.000000
Noordwijk          White                      1.000000              2.500000

In [33]:
differential_frame_2026 = differential_frame[differential_frame.Date >= '2026-01-01']

In [34]:
differential_frame_2026.head()

,Course,Tee,Date,Differential Hole 1,Differential Hole 2,Differential Hole 3,Differential Hole 4,Differential Hole 5,Differential Hole 6,Differential Hole 7,...,Differential Hole 9,Differential Hole 10,Differential Hole 11,Differential Hole 12,Differential Hole 13,Differential Hole 14,Differential Hole 15,Differential Hole 16,Differential Hole 17,Differential Hole 18
109,KHGCC,White (V2),2026-03-15,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,-1.0
110,KHGCC,White (V2),2026-05-17,-2.0,0.0,1.0,1.0,-1.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,-1.0
111,KHGCC,Yellow (V2),2026-05-23,-1.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,1.0,1.0,-1.0,1.0,0.0,0.0,0.0,2.0
112,KHGCC,White (V2),2026-06-27,0.0,1.0,0.0,0.0,-1.0,0.0,0.0,...,1.0,-1.0,0.0,1.0,0.0,2.0,1.0,0.0,0.0,0.0
113,KHGCC,White (V2),2026-08-02,0.0,1.0,0.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0

In [35]:
score_cols = [col for col in differential_frame_2026.columns if 'Differential' in col]

In [36]:
differential_frame_2026.groupby('Tee')[score_cols].sum()

,Differential Hole 1,Differential Hole 2,Differential Hole 3,Differential Hole 4,Differential Hole 5,Differential Hole 6,Differential Hole 7,Differential Hole 8,Differential Hole 9,Differential Hole 10,Differential Hole 11,Differential Hole 12,Differential Hole 13,Differential Hole 14,Differential Hole 15,Differential Hole 16,Differential Hole 17,Differential Hole 18
Tee,,,,,,,,,,,,,,,,,,
White (V2),-2.0,2.0,1.0,2.0,-1.0,6.0,2.0,3.0,1.0,0.0,1.0,2.0,2.0,5.0,2.0,2.0,1.0,-1.0
Yellow (V2),-1.0,2.0,0.0,2.0,0.0,3.0,1.0,1.0,1.0,0.0,4.0,1.0,0.0,3.0,2.0,1.0,0.0,4.0

In [37]:
differential_frame_2026.groupby('Tee')[score_cols].sum() / differential_frame_2026.groupby('Tee')[score_cols].count()

,Differential Hole 1,Differential Hole 2,Differential Hole 3,Differential Hole 4,Differential Hole 5,Differential Hole 6,Differential Hole 7,Differential Hole 8,Differential Hole 9,Differential Hole 10,Differential Hole 11,Differential Hole 12,Differential Hole 13,Differential Hole 14,Differential Hole 15,Differential Hole 16,Differential Hole 17,Differential Hole 18
Tee,,,,,,,,,,,,,,,,,,
White (V2),-0.400000,0.400000,0.2,0.400000,-0.2,1.2,0.400000,0.600000,0.200000,0.0,0.200000,0.400000,0.4,1.0,0.400000,0.400000,0.2,-0.200000
Yellow (V2),-0.333333,0.666667,0.0,0.666667,0.0,1.0,0.333333,0.333333,0.333333,0.0,1.333333,0.333333,0.0,1.0,0.666667,0.333333,0.0,1.333333